# Generated by Django 3.2.18 on 2023-04-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(max_length=100)),
                ('image', models.ImageField(default='../uppbeat_logo_gh4ogf', upload_to='images/')),
                ('premium_track', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('Once', 'Once'), ('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Monthly', 'Monthly'), ('Biannually', 'Biannually'), ('Annually', 'Annually')], default='once', max_length=32)),
                ('add_playlist', models.BooleanField(default=False)),
                ('add_favourite', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['track_name'],
            },
        ),
    ]
